#!/usr/bin/env python3
"""Write Docs/credits/cars.md from shortlist.json + the processed outputs.

Run after the cars are processed: Tools/.venv/bin/python Tools/cars/write_credits.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
CARS = os.path.join(REPO, "Game", "Assets", "InkDrift", "Models", "Cars")

GAME = {
    "hachi": ("HACHI GR8", "hachi/hachi.fbx"),
    "kaiju": ("KAIJU SPR-X", "kaiju/kaiju.fbx"),
    "zenkai": ("ZENKAI Z", "zenkai/zenkai.fbx"),
    "raijin": ("RAIJIN BX-R", "raijin/raijin.fbx"),
    "tsubame": ("TSUBAME RS", "tsubame/tsubame.fbx"),
    "kei": ("Traffic: kei truck", "Traffic/traffic_kei.fbx"),
    "taxi": ("Traffic: taxi", "Traffic/traffic_taxi.fbx"),
    "van": ("Traffic: delivery van", "Traffic/traffic_van.fbx"),
    "truck": ("Traffic: box truck", "Traffic/traffic_truck.fbx"),
}
LICENSE = {"by": ("CC-BY 4.0", "https://creativecommons.org/licenses/by/4.0/"),
           "cc0": ("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/")}

HERO_CHANGES = ("converted to FBX, re-oriented and rescaled to real-world size, re-pivoted; all manufacturer "
                "badges, emblems and brand text removed (badge meshes deleted, logo textures painted out/dropped); "
                "materials merged and renamed to the game's slots, body-paint textures stripped; mesh decimated "
                "and normals recalculated; ride height lowered and wheels pushed out flush; aero kit added "
                "(GT wing, front splitter, canards, side skirts); fictional Japanese number plates and INK DRIFT "
                "livery decals added")
TRAFFIC_CHANGES = ("converted to FBX, re-oriented and rescaled to real-world size, re-pivoted; manufacturer "
                   "badges, emblems and brand text removed; materials merged and renamed to the game's slots; "
                   "mesh decimated for traffic use; fictional Japanese number plates added")


def main():
    sl = json.load(open(os.path.join(HERE, "shortlist.json")))
    lines = [
        "# Car model credits — INK DRIFT: TOKYO",
        "",
        "All vehicles are **fictional look-alikes**: every manufacturer logo, badge, emblem and brand text was",
        "removed and the cars carry invented names. The 3D models are based on the Sketchfab models below,",
        "used under their Creative Commons licenses. **They have been modified** (changes listed per model).",
        "The source models are not endorsed by, and are unrelated to, the car manufacturers.",
        "",
        "Livery decals come from `Game/Assets/InkDrift/Art/Decals/` (original project art, see `art.md`);",
        "number plates and the windshield banner are generated by `Tools/cars/cartex.py` with the project's",
        "OFL fonts (Noto Sans JP, Dela Gothic One). The pipeline is `Tools/cars/prep_car.py`.",
        "",
        "| Game asset | File | Source model | Author | License |",
        "|---|---|---|---|---|",
    ]
    details = []
    for slot, e in sl["cars"].items():
        c = next(c for c in e["candidates"] if c["uid"] == e["chosen"])
        name, path = GAME[slot]
        fbx = os.path.join(CARS, path)
        if not os.path.exists(fbx):
            continue
        lic, lic_url = LICENSE[c["license"]["slug"]]
        author = c.get("authorName") or c["author"]
        lines.append(f"| {name} | `Models/Cars/{path}` | [{c['name']}]({c['url']}) | "
                     f"[{author}](https://sketchfab.com/{c['author']}) | [{lic}]({lic_url}) |")
        changes = TRAFFIC_CHANGES if slot in ("kei", "taxi", "van", "truck") else HERO_CHANGES
        note = ""
        if slot == "raijin":
            note = (" Stand-in for the GR Corolla look: no GR Corolla / GR Yaris with a trustworthy CC-BY/CC0 origin "
                    "was available, so the 2022+ AWD Subaru WRX (VB) body is used.")
        if slot == "zenkai":
            note = " The source is the Nissan Z Proto, the near-identical concept of the production RZ34."
        details += [
            f"### {name}",
            f"- Source: \"{c['name']}\" by {author} — {c['url']}",
            f"- License: {lic} ({lic_url}) — attribution: \"{c['name']}\" by {author}, licensed under {lic}.",
            f"- Modifications: {changes}.{note}",
            "",
        ]
    lines += ["", "## Attribution and changes", ""] + details
    out = os.path.join(REPO, "Docs", "credits", "cars.md")
    with open(out, "w") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
